package guru.springframework.spring6webapp.domain;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;

@Entity
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String firstName;
    private String lastName;

    // authors is the name of the variable defined in the Book class.
    @ManyToMany(mappedBy = "authors")
    private Set<Book> books = new HashSet<>(); 

    public Set<Book> getBooks() {
        return books;
    }
    public void setBooks(Set<Book> books) {
        this.books = books;
    }
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Override
    public String toString() {
        return "Author [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", books=" + books + "]";
    }

    @Override
    public int hashCode() {
        // Generated by vscode and plugins
        // final int prime = 31;
        // int result = 1;
        // result = prime * result + ((id == null) ? 0 : id.hashCode());
        // return result;
        // Just to follow the example with intelliJ
        return getId() != null ? getId().hashCode() : 0; 
    }
    @Override
    public boolean equals(Object obj) {
        // if (this == obj)
        //     return true;
        // if (obj == null)
        //     return false;
        // if (getClass() != obj.getClass())
        //     return false;
        // Author other = (Author) obj;
        // if (id == null) {
        //     if (other.id != null)
        //         return false;
        // } else if (!id.equals(other.id))
        //     return false;
        // return true;
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Author)) return false;
        Author author = (Author) obj;
        
        return getId() != null ? getId().equals(author.getId()) : author.getId() == null;
    }

    


}
